#ifndef GITLAB_DESKTOP_MONITOR_RESPONSESTATUS_H
#define GITLAB_DESKTOP_MONITOR_RESPONSESTATUS_H

enum class ResponseStatus {
    SUCCESSFUL,
    UNSUCCESSFUL,
};

#endif //GITLAB_DESKTOP_MONITOR_RESPONSESTATUS_H
