#ifndef GITLAB_DESKTOP_MONITOR_RESPONSESTATUS_H
#define GITLAB_DESKTOP_MONITOR_RESPONSESTATUS_H

enum class ResponseStatus {
    SUCCESSFUL,
    TIMEOUT,
    INTERNAL_SERVER_ERROR,
    AUTHENTICATION_REQUIRED_ERROR,
    HOST_NOT_FOUND_ERROR,
    UNSUCCESSFUL,
};

#endif //GITLAB_DESKTOP_MONITOR_RESPONSESTATUS_H
